version: '3.8'

volumes:
  docker-postgres:
networks:
  postgres:
    name: rest-serivce
    driver: bridge

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: npm run start:dev
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    environment:
      - PORT=${PORT}
      - DB_SCHEMA=${POSTGRES_USER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_USER}
      - DB_HOST=${POSTGRES_USER}
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
